### ISSUE TITLE
Adobe DIM Dataset

### ISSUE THREAD

**Issue by rishab-sharma** [bluestyle97/semantic-human-matting#1]
Hi,
As mentioned in the paper blog to contact the author for the dataset, but the author is no longer responding. 

Can you please provide the link to the dataset. My email: rishabsharmaddn@gmail.com

Best Regards,
Rishab

**Comment by xiezhang666** [comment]
Hi,  I would like to train the model in your paper "Deep Image Matting" with your code. but the author is no longer responding.
Can you send me the dataset of that paper?    My email:  xiejun@lenovol.com
Best Regards,
xiejun
