### ISSUE TITLE
Question about test mode

### ISSUE THREAD

**Issue by Zonglin-Li** [bluestyle97/semantic-human-matting#2]
Can you tell me how to run the test mode?

Thank you so much

**Comment by bluestyle97** [comment]
> Can you tell me how to run the test mode?
> 
> Thank you so much

Hi, you can simply create a new configuration file “test.yaml” and write something like:

mode: test
cuda: true
ngpu: 2
mnet_checkpoint: checkpoint-epoch20.pth.tar
data_root: /root/datasets/Matting/Adobe_DIM/
batch_size: 32

Then run the code with this configuration file. I hope this can be helpful for you.
